wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("wiki/<str:title>/edit", views.edit, name="edit"),
    path("wiki/<str:title>/delete", views.delete, name="delete"),
    path("search", views.search, name="search"),
    path("new", views.new, name="new"),
    path("random", views.random, name="random"),
    path("<str:title>", views.not_found, name="404")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from random import choice

from . import util

class NewEntry(forms.Form):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea)

def entry_exists(title):
    return title.lower() in (name.lower() for name in util.list_entries())

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    entry = util.get_entry(title)
    if entry:
        return render(request, "encyclopedia/entry.html", {'title': title, 'entry': entry})
    else:
        return redirect("encyclopedia:404", title=title)

def search(request):
    if request.method == 'POST':
        q = request.POST['q']
        if q and entry_exists(q):
            return redirect("encyclopedia:entry", title=q)
        return render(request, "encyclopedia/404.html", {
            'title': q,
            'entries': [name for name in util.list_entries() if q.lower() in name.lower()]
        })

def new(request):
    if request.method == "POST":
        form = NewEntry(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]

            if entry_exists(title):
                return render(request, "encyclopedia/exists.html", {'title': title})

            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return redirect("encyclopedia:entry", title=title)
        else:
            return render(request, "encyclopedia/form.html", {'form': form})
    return render(request, "encyclopedia/form.html", {'form': NewEntry()})

def edit(request, title):
    if request.method == "POST":
        if entry_exists(title):
            form = NewEntry({"title": title, "content": request.POST["content"]})
            if form.is_valid():
                util.save_entry(title, form.cleaned_data["content"])
                return redirect("encyclopedia:entry", title=title)
            else:
                context["form"] = form
                return render(request, "encyclopedia/form.html", {"form": form})
        else:
            return redirect("encyclopedia:404", title=title)

    entry = util.get_entry(title)
    if entry:
        return render(request, "encyclopedia/form.html", {"form": NewEntry({'title': title, 'content': entry})})
    else:
        return Http404()

def random(request):
    title = choice(util.list_entries())
    return redirect("encyclopedia:entry", title=title)

def delete(request, title):
    return redirect("encyclopedia:index")

def not_found(request, title):
    return render(request, "encyclopedia/404.html", {"title": title})

        
    

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <div>
        <a href="{% url 'encyclopedia:edit' title %}">Edit</a>
        <a href="{% url 'encyclopedia:delete' title %}">Delete</a>
    </div>

    {{ entry|safe }}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/exists.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}Page already exists{% endblock %}

{% block body %}
    <p>Page <a href="{% url 'encyclopedia:entry' title %}">{{ title }}</a> already exists</p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/form.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}Add new page{% endblock %}

{% block body %}
    <h1>
        {% if form.is_bound %}{{ form.title.value }}: edit
        {% else %}Create a new page
        {% endif%}
    </h1>
    <form method="POST" action="
    {% if form.is_bound %}
        {% url 'encyclopedia:edit' form.title.value %}
    {% else %}
        {% url 'encyclopedia:new' %}
    {% endif %}">
        {% csrf_token %}
        {% if form.is_bound %}
            {{ form.content }}
        {% else %}
            {{ form }}
        {% endif %}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>